set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
" Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'tpope/vim-commentary'
Plugin 'nvie/vim-flake8'
" git repos on your local machine (i.e. when working on your own plugin)
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
set nu
colorscheme evening
inoremap jk <Esc>
set nocompatible              " be iMproved, required
set encoding=utf-8
set tabstop=4 "Count four spaces for a tab
set shiftwidth=4 " Cols when use << and >> to indent
set expandtab " Replace tabs with spaces
set autoindent
set cindent
"Control how many columns vim uses when you hit Tab in insert mode
set softtabstop=4
set backspace=indent,eol,start
if !exists("g:syntax_on")
    syntax enable
endif
set cursorline " Highlight current line
set cursorcolumn " Highlight current col
set colorcolumn=80 "Set ruler
let mapleader = "-" " Set the global leader
