" Display {{{

    set encoding=utf-8
    syntax enable " Turn on the syntax highlight
    set nu " Show line numbers

    " Indent settings
    set tabstop=4 "Count four spaces for a tab
    set shiftwidth=4 " Cols when use << and >> to indent

    "Control how many columns vim uses when you hit Tab in insert mode.
    set softtabstop=4

    set expandtab " Replace tabs with spaces
    set autoindent
    set cindent

    set cursorline " Highlight current line
    set cursorcolumn " Highlight current col
    set fdc=1 " FoldColumn Width

    " Some color settings
    hi CursorLine cterm=NONE ctermbg=black
    hi CursorColumn cterm=NONE ctermbg=black
    hi Folded cterm=NONE ctermbg=green ctermfg=black
    hi FoldColumn cterm=NONE ctermbg=green ctermfg=black
    hi CursorLineNR cterm=bold ctermbg=yellow ctermfg=black
    set list lcs=tab:▸•,trail:• " Set listchars

" }}}

" Mappings {{{

    let mapleader = "-" " Set the global leader
    inoremap jk <Esc>
    nnoremap H ^
    nnoremap L $

    " Open the vimrc file, and source it.
    nnoremap <leader>ev :vsplit $MYVIMRC<cr>
    nnoremap <leader>sv :source $MYVIMRC<cr>

    " Toggle relative line numbers.
    nnoremap <leader>n :set rnu!<cr>

    " Add command alias.
    command! W w

    " Use space to toggle foldings.
    nnoremap <space> zA

    " Use ctrl-[hjkl] the active split!
    nnoremap <silent> <c-k> :wincmd k<CR>
    nnoremap <silent> <c-j> :wincmd j<CR>
    nnoremap <silent> <c-h> :wincmd h<CR>
    nnoremap <silent> <c-l> :wincmd l<CR>

" }}}

" Status line{{{

    set laststatus=2      " Display the status line always
    set statusline=%=     " Switch to the right side
    set statusline+=[%{strftime('%Y\ %a\ %b\ %d\ %H:%M:%S')}] " Date time
    set statusline+=\ -\  " Separator
    set statusline+=[%F]  " Path to the file
    set statusline+=\ -\  " Separator
    set statusline+=%y    " File type of the file
    set statusline+=\ -\  " Separator
    set statusline+=row:[%3l   " Current line
    set statusline+=/ " Separator
    set statusline+=%-3L]\    " Total lines
    set statusline+=col:[%2c]\   " Current column number

    " Timer callback function to update status line
    func! UpdateStatusLine(timer)
        redraws!
    endfunc

    " Update status line per sec
    let statuslineTimer = timer_start(1000, 'UpdateStatusLine', {'repeat':-1})
" }}}

" Folding {{{
    augroup filetype_vim
      autocmd!
      autocmd FileType vim setlocal foldmethod=marker
      autocmd FileType python setlocal foldmethod=indent
    augroup END
" }}}

" Search {{{
    set hlsearch " Highlight the search results
    set incsearch " Incremental search
"}}}
